# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Auto Stop Race' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Auto Stop Race

  target 'Auto Stop RaceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Auto Stop RaceUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
