disabled_rules:
  - identifier_name
  - trailing_whitespace
  - trailing_newline
  - line_length
  - todo
  - force_cast
  - type_name
  - weak_delegate

included:
  - Auto Stop Race

warning_threshold: 2